# Python Libraries
* Python library is a collection of functions and methods that allows you to perform many actions without writing your code.

### Python NumPy
* NumPy stands for Numerical python and is the core library for numeric and scientific computing.
* It consits of multi-dimensional arry objects and a collection of routines for processing those arrays .

In [5]:
# Single Dimensional Array
import numpy as np

n1 = np.array([1, 2, 3, 4])
print(n1)

[1 2 3 4]


In [8]:
# Multi-dimensional Array
import numpy as np 

n2 = np.array([[4, 5, 6, 7], [9, 8, 7, 6]])
print(n2)

[[4 5 6 7]
 [9 8 7 6]]


* Initializing NumPy array with zeros

In [3]:
import numpy as np
n1 = np.zeros((1,2))                # 1 is row and 2 is column
print(n1)

[[0. 0.]]


In [6]:
import numpy as np
n1 = np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
import numpy as np

In [9]:
n1 = np.full((2, 3),4)
print(n1)

[[4 4 4]
 [4 4 4]]


In [11]:
n1 = np.arange(28, 34)
n1

array([28, 29, 30, 31, 32, 33])

In [14]:
n1 = np.arange(14, 75, 6)
print(n1)

[14 20 26 32 38 44 50 56 62 68 74]
