# Python Libraries
* Python library is a collection of functions and methods that allows you to perform many actions without writing your code.

### Python NumPy
* NumPy stands for Numerical python and is the core library for numeric and scientific computing.
* It consits of multi-dimensional arry objects and a collection of routines for processing those arrays .

In [5]:
# Single Dimensional Array
import numpy as np

n1 = np.array([1, 2, 3, 4])
print(n1)

[1 2 3 4]


In [8]:
# Multi-dimensional Array
import numpy as np 

n2 = np.array([[4, 5, 6, 7], [9, 8, 7, 6]])
print(n2)

[[4 5 6 7]
 [9 8 7 6]]
