# Python Libraries
* Python library is a collection of functions and methods that allows you to perform many actions without writing your code.

### Python NumPy
* NumPy stands for Numerical python and is the core library for numeric and scientific computing.
* It consits of multi-dimensional arry objects and a collection of routines for processing those arrays .

In [2]:
# Single Dimensional Array
import numpy as np

n1 = np.array([1, 2, 3, 4])
print(n1)

[1 2 3 4]


In [3]:
# Multi-dimensional Array
import numpy as np 

n2 = np.array([[4, 5, 6, 7], [9, 8, 7, 6]])
print(n2)

[[4 5 6 7]
 [9 8 7 6]]


* Initializing NumPy array with zeros

In [4]:
import numpy as np
n1 = np.zeros((1,2))                # 1 is row and 2 is column
print(n1)

[[0. 0.]]


In [5]:
import numpy as np
n1 = np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np

In [7]:
n1 = np.full((2, 3),4)
print(n1)

[[4 4 4]
 [4 4 4]]


In [8]:
n1 = np.arange(28, 34)
n1

array([28, 29, 30, 31, 32, 33])

In [9]:
n1 = np.arange(15, 75, 5)
print(n1)

[15 20 25 30 35 40 45 50 55 60 65 70]


In [12]:
n1 = np.arange(50,500,10)
print(n1)

[ 50  60  70  80  90 100 110 120 130 140 150 160 170 180 190 200 210 220
 230 240 250 260 270 280 290 300 310 320 330 340 350 360 370 380 390 400
 410 420 430 440 450 460 470 480 490]


In [17]:
n1 = np.random.randint(2, 250, 10)          # Between the range of 2 to 250 it will gives random ten numbers
print(n1)

[ 23  37  97  94 194 123  21 203 245  58]


In [19]:
n1 = np.array([[1,2,3,4], [5,6,7,8]])
print(n1)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
n1.shape = (4,2)
print(n1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
